"""系统各边界使用的严格 Pydantic 契约。

所有模型都禁止未知字段（StrictModel），因此组件之间发生漂移时，会在边界处
明确失败，而不是在下游悄悄出错：

    tools.py       工具参数/结果——面向模型的接口，由 TOOL_VERSION 进行版本化
                   （任何语义变化都必须递增版本）
    model.py       与提供商无关的消息、流事件和用量
    events.py      类型化的追踪流（ApplicationEvent 联合类型）
    checkpoint.py  用于快速恢复的版本化快照（CheckpointV1）
"""

from haven.contracts.base import StrictModel
from haven.contracts.checkpoint import (
    CHECKPOINT_SCHEMA_VERSION,
    BudgetSnapshot,
    CheckpointV1,
    EvidenceSnapshot,
    UsageSnapshot,
)
from haven.contracts.events import (
    EVENT_ADAPTER,
    SCHEMA_VERSION,
    TRANSIENT_KINDS,
    ApplicationEvent,
    ApprovalDecided,
    ApprovalRequested,
    AssistantDelta,
    ContextBuilt,
    ContextSegment,
    DiffPreview,
    EffectUnknown,
    EventEnvelope,
    EvidenceRecorded,
    ExecutionStarted,
    ModelCompleted,
    Notice,
    PlanStepView,
    PlanUpdated,
    PolicyDecided,
    RunCreated,
    RunFinished,
    StepStarted,
    ToolCompleted,
    ToolProposed,
)
from haven.contracts.model import (
    ModelEvent,
    ModelMessage,
    ModelRequest,
    ModelResult,
    StreamFinished,
    TextDelta,
    ToolCallProposal,
    ToolCallReady,
    ToolSchema,
    Usage,
    UsageReport,
)
from haven.contracts.tools import (
    ARGS_MODELS,
    TOOL_DESCRIPTIONS,
    TOOL_VERSION,
    PlanStep,
    RecipeSpec,
    RepoCheckArgs,
    RepoCreateArgs,
    RepoDiffArgs,
    RepoEditArgs,
    RepoListArgs,
    RepoReadArgs,
    RepoSearchArgs,
    TaskPlanArgs,
    ToolArgs,
    ToolResult,
    tool_schemas,
)

__all__ = [
    "ARGS_MODELS",
    "CHECKPOINT_SCHEMA_VERSION",
    "EVENT_ADAPTER",
    "SCHEMA_VERSION",
    "TOOL_DESCRIPTIONS",
    "TOOL_VERSION",
    "TRANSIENT_KINDS",
    "ApplicationEvent",
    "ApprovalDecided",
    "ApprovalRequested",
    "AssistantDelta",
    "BudgetSnapshot",
    "CheckpointV1",
    "ContextBuilt",
    "ContextSegment",
    "DiffPreview",
    "EffectUnknown",
    "EventEnvelope",
    "EvidenceRecorded",
    "EvidenceSnapshot",
    "ExecutionStarted",
    "ModelCompleted",
    "ModelEvent",
    "ModelMessage",
    "ModelRequest",
    "ModelResult",
    "Notice",
    "PlanStep",
    "PlanStepView",
    "PlanUpdated",
    "PolicyDecided",
    "RecipeSpec",
    "RepoCheckArgs",
    "RepoCreateArgs",
    "RepoDiffArgs",
    "RepoEditArgs",
    "RepoListArgs",
    "RepoReadArgs",
    "RepoSearchArgs",
    "RunCreated",
    "RunFinished",
    "StepStarted",
    "StreamFinished",
    "StrictModel",
    "TaskPlanArgs",
    "TextDelta",
    "ToolArgs",
    "ToolCallProposal",
    "ToolCallReady",
    "ToolCompleted",
    "ToolProposed",
    "ToolResult",
    "ToolSchema",
    "Usage",
    "UsageReport",
    "UsageSnapshot",
    "tool_schemas",
]
