"""Strict Pydantic contracts for every boundary of the system.

All models forbid unknown fields (StrictModel), so drift between components
fails loudly at the boundary instead of silently downstream:

    tools.py       tool args/results - the model-facing surface, versioned
                   by TOOL_VERSION (bumped on any semantic change)
    model.py       provider-neutral messages, stream events, usage
    events.py      the typed trace stream (ApplicationEvent union)
    checkpoint.py  the versioned fast-resume snapshot (CheckpointV1)
"""

from haven.contracts.base import StrictModel
from haven.contracts.checkpoint import (
    CHECKPOINT_SCHEMA_VERSION,
    BudgetSnapshot,
    CheckpointV1,
    EvidenceSnapshot,
    UsageSnapshot,
)
from haven.contracts.events import (
    EVENT_ADAPTER,
    SCHEMA_VERSION,
    TRANSIENT_KINDS,
    ApplicationEvent,
    ApprovalDecided,
    ApprovalRequested,
    AssistantDelta,
    ContextBuilt,
    ContextSegment,
    DiffPreview,
    EffectUnknown,
    EventEnvelope,
    EvidenceRecorded,
    ExecutionStarted,
    ModelCompleted,
    Notice,
    PlanStepView,
    PlanUpdated,
    PolicyDecided,
    RunCreated,
    RunFinished,
    StepStarted,
    ToolCompleted,
    ToolProposed,
)
from haven.contracts.model import (
    ModelEvent,
    ModelMessage,
    ModelRequest,
    ModelResult,
    StreamFinished,
    TextDelta,
    ToolCallProposal,
    ToolCallReady,
    ToolSchema,
    Usage,
    UsageReport,
)
from haven.contracts.tools import (
    ARGS_MODELS,
    TOOL_DESCRIPTIONS,
    TOOL_VERSION,
    PlanStep,
    RecipeSpec,
    RepoCheckArgs,
    RepoCreateArgs,
    RepoDiffArgs,
    RepoEditArgs,
    RepoListArgs,
    RepoReadArgs,
    RepoSearchArgs,
    TaskPlanArgs,
    ToolArgs,
    ToolResult,
    tool_schemas,
)

__all__ = [
    "ARGS_MODELS",
    "CHECKPOINT_SCHEMA_VERSION",
    "EVENT_ADAPTER",
    "SCHEMA_VERSION",
    "TOOL_DESCRIPTIONS",
    "TOOL_VERSION",
    "TRANSIENT_KINDS",
    "ApplicationEvent",
    "ApprovalDecided",
    "ApprovalRequested",
    "AssistantDelta",
    "BudgetSnapshot",
    "CheckpointV1",
    "ContextBuilt",
    "ContextSegment",
    "DiffPreview",
    "EffectUnknown",
    "EventEnvelope",
    "EvidenceRecorded",
    "EvidenceSnapshot",
    "ExecutionStarted",
    "ModelCompleted",
    "ModelEvent",
    "ModelMessage",
    "ModelRequest",
    "ModelResult",
    "Notice",
    "PlanStep",
    "PlanStepView",
    "PlanUpdated",
    "PolicyDecided",
    "RecipeSpec",
    "RepoCheckArgs",
    "RepoCreateArgs",
    "RepoDiffArgs",
    "RepoEditArgs",
    "RepoListArgs",
    "RepoReadArgs",
    "RepoSearchArgs",
    "RunCreated",
    "RunFinished",
    "StepStarted",
    "StreamFinished",
    "StrictModel",
    "TaskPlanArgs",
    "TextDelta",
    "ToolArgs",
    "ToolCallProposal",
    "ToolCallReady",
    "ToolCompleted",
    "ToolProposed",
    "ToolResult",
    "ToolSchema",
    "Usage",
    "UsageReport",
    "UsageSnapshot",
    "tool_schemas",
]
